# specify java as the language
language: java

jdk:
  - oraclejdk8

# python versions to be used for testing
python:
  - "2.7"

install:
  - sudo apt-get install ant sox
  - export JYTHON_URL='http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar'
  - mkdir -p /home/travis/virtualenv/jython
  - wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d /home/travis/virtualenv/jython; export PATH=/home/travis/virtualenv/jython/bin:$PATH;

before_script:
  - /home/travis/virtualenv/jython/bin/jython --version
  - python --version
  - java -version
  - uname -a
  - ls -li .
  - mkdir -p ./config
  - touch ./config/environment.ini
  - ls -li ./config
  - echo -e "python.security.respectJavaAccessibility = false" >> /home/travis/virtualenv/jython/registry
  - echo -e "[PATHS]\njython_home:/home/travis/virtualenv/jython\njython_exec:/home/travis/virtualenv/jython/bin/jython" > ./config/environment.ini

script: python run_tests test_converter

# Notify the mailing list
notifications:
  email:
    on_success: change
    on_failure: always
