# Main settings
git_tag: 0.9.20
archive_extension: "zip"
URL: "https://github.com/Catrobat/Catroid/archive/%{tag_name}.%{archive_extension}"
xstream_download_URL: "http://repo.maven.apache.org/maven2/com/thoughtworks/xstream/xstream/1.4.7/xstream-1.4.7.jar"
download_path: "./workspace/input"
extraction_path: "./workspace/output/src"
relative_code_source_path: "catroid/src"

# Include/exclude settings
removed_classes:
    [LegoNXTSetting, LegoNxtMotorMoveBrick, LegoNxtMotorStopBrick,
    LegoNxtMotorTurnAngleBrick, LegoNxtPlayToneBrick, PhiroMotorMoveBackwardBrick,
    PhiroMotorMoveForwardBrick, PhiroMotorStopBrick, PhiroPlayToneBrick,
    PhiroRGBLightBrick, PhiroIfLogicBeginBrick, ArduinoSendDigitalValueBrick, ArduinoSendPWMValueBrick]

additional_serialization_classes:
    - AllowedAfterDeadEndBrick
    - Brick
    - Constants
    - DeadEndBrick
    - DroneBrick
    - DroneMoveBrick
    - ElementType
    - Formula
    - FormulaElement
    - Functions
    - Operators
    - NestingBrick
    - ScreenModes
    - ScreenValues
    - ScriptBrick
    - Sensors
    - Look
    - StorageHandler
    - ProjectManager
    - UserListBrick
    - UserVariableBrick

preserved_interfaces:
    [Brick, BroadcastMessage, Converter, LoopBeginBrick, MindstormsSensor,
    MindstormsCommand]

additional_helper_classes:
    - BroadcastMessage
    - Constants
    - CatroidFieldKeySorter
    - UserVariablesContainer
    - ConcurrentFormulaHashMap
    - XStreamBrickConverter
    - XStreamConcurrentFormulaHashMapConverter
    - XStreamScriptConverter
    - XStreamSettingConverter
    - LOOKUP
    - XStreamToSupportCatrobatLanguageVersion097AndBefore # introduced in v0.97
    - XStreamUserVariableConverter
    # exception classes
    - ProjectException
    - CompatibilityProjectException
    - LoadingProjectException
    - OutdatedVersionProjectException
    - FileChecksumContainer

class_to_preserved_fields_mapping:
    BroadcastReceiverBrick:
        - broadcastMessage
    FormulaElement:
        - parent
    PlaySoundBrick:
        - oldSelectedSound
    PointToBrick:
        - oldSelectedObject
    Script:
        - brick
    Sprite:
        [look, isPaused, newUserBrickNext]
    SetLookBrick:
        - oldSelectedLook
    UserVariable:
        - value
    WhenScript:
        - position
    ProjectManager:
        [INSTANCE, project, currentScript, currentSprite, currentUserBrick]
    IfLogicBeginBrick:
        [ifElseBrick, ifEndBrick]
    IfLogicElseBrick:
        [ifBeginBrick, ifEndBrick]
    IfLogicEndBrick:
        [ifBeginBrick, ifElseBrick]
    ForeverBrick:
        - loopEndBrick
    RepeatBrick:
        - loopEndBrick
    LoopEndBrick:
        - loopBeginBrick
    UserBrick:
        - lastDataVersion
    UserScriptDefinitionBrick:
        - brick
    UserScriptDefinitionBrickElements:
        - version
    UserList:
        - list
    UserBrickParameter:
        - parent
    SetVariableBrick:
        - defaultPrototypeToken

class_to_preserved_methods_mapping:
    Functions:
        - isFunction
        - getFunctionByValue
    BroadcastScript:
        - setBroadcastMessage
        - getBroadcastMessage
        - getScriptBrick
    StartScript:
        - getScriptBrick
    WhenScript:
        - getScriptBrick
    Project:
        - ifLandscapeSwitchWidthAndHeight
        - ifPortraitSwitchWidthAndHeight
        - addSprite
        - setName
        - getName
    SoundInfo:
        - compareTo
        - setTitle
        - getTitle
    LookData:
        - setLookFilename
    FormulaElement:
        - getRoot
        - replaceElement
        - replaceWithSubElement
        - clone
    Formula:
        - getRoot
        - clone
    PlaySoundBrick:
        - setSoundInfo
    StorageHandler:
        - getInstance
        - setXstreamAliases
        - getXMLStringOfAProject
    ScriptBrick:
        - getScriptSafe
    Sprite:
        - getLookDataList
        - getScript
        - getScriptIndex
        - getNumberOfScripts
        - getUserBrickList
        - addScript
    UserVariablesContainer:
        - addSpriteUserVariableToSprite
        - getOrCreateVariableListForSprite
    FormulaBrick:
        - addAllowedBrickField
        - getFormulaWithBrickField
        - setFormulaWithBrickField
    DataContainer:
        - addUserBrickVariable
        - addUserBrickUserVariableToUserBrick
        - addSpriteUserVariable
        - addSpriteUserVariableToSprite
        - addProjectUserVariable
        - getOrCreateVariableListForUserBrick
        - getOrCreateVariableListForSprite
        - cleanVariableListForSprite
        - getUserVariable
        - getUserVariableContext
        - findUserVariable
        - getUserList
        - addSpriteUserList
        - addSpriteUserListToSprite
        - addProjectUserList
        - getOrCreateUserListListForSprite
        - findUserList
        - getUserList"
    AddItemToUserListBrick:
        - initializeBrickFields
    ChangeTransparencyByNBrick:
        - initializeBrickFields
    DeleteItemOfUserListBrick:
        - initializeBrickFields
    InsertItemIntoUserListBrick:
        - initializeBrickFields
    ReplaceItemInUserListBrick:
        - initializeBrickFields
    SetTransparencyBrick:
        - initializeBrickFields
    LoopBeginBrick:
        - getLoopEndBrick
        - setLoopEndBrick
    DroneMoveBrick:
        - initializeBrickFields
    GlideToBrick:
        - initializeBrickFields
    ChangeBrightnessByNBrick:
        - initializeBrickFields
    ChangeGhostEffectByNBrick:
        - initializeBrickFields
    ChangeSizeByNBrick:
        - initializeBrickFields
    ChangeVariableBrick:
        - initializeBrickFields
    ChangeVolumeByNBrick:
        - initializeBrickFields
    ChangeXByNBrick:
        - initializeBrickFields
    ChangeYByNBrick:
        - initializeBrickFields
    GoNStepsBackBrick:
        - initializeBrickFields
    IfLogicBeginBrick:
        - initializeBrickFields
    MoveNStepsBrick:
        - initializeBrickFields
    NoteBrick:
        - initializeBrickFields
    PlaceAtBrick:
        - initializeBrickFields
    PointInDirectionBrick:
        - initializeBrickFields
    RepeatBrick:
        - initializeBrickFields
    SetBrightnessBrick:
        - initializeBrickFields
    SetGhostEffectBrick:
        - initializeBrickFields
    SetSizeToBrick:
        - initializeBrickFields
    SetVariableBrick:
        - initializeBrickFields
    SetVolumeToBrick:
        - initializeBrickFields
    SetXBrick:
        - initializeBrickFields
    SetYBrick:
        - initializeBrickFields
    SpeakBrick:
        - initializeBrickFields
    TurnLeftBrick:
        - initializeBrickFields
    TurnRightBrick:
        - initializeBrickFields
    VibrationBrick:
        - initializeBrickFields
    WaitBrick:
        - initializeBrickFields
    ShowTextBrick:
        - initializeBrickFields
    UserBrick:
        - getUserScriptDefinitionBrickElements
        - copyFormulasMatchingNames
    UserScriptDefinitionBrick:
        - setUserBrick
        - getScriptSafe
    UserScriptDefinitionBrickElements:
        - getUserScriptDefinitionBrickElementList
    WhenBrick:
        - getScriptSafe
    BroadcastReceiverBrick:
        - getScriptSafe
    WhenStartedBrick:
        - getScriptSafe
    ProjectManager:
        - getInstance
        - addSprite
        - addScript
        - spriteExists

remove_fields_mapping:
    Constants:
        [DEFAULT_ROOT, TMP_PATH, TMP_IMAGE_PATH, TEXT_TO_SPEECH_TMP_PATH]
    Look:
        [actionsToRestart, pixmap, whenParallelAction, shader]
    NXTSensor:
        - connection

remove_methods_mapping:
    ProjectManager:
        [uploadProject, loadProject, cancelLoadProject, canLoadProject, saveProject,
        initializeDefaultProject, initializeDroneProject, initializeNewProject,
        deleteCurrentProject, deleteProject, renameProject, addSprite,
        addScript, spriteExists]
    Look:
        [copyLookForSprite, createBrightnessContrastShader, checkImageChanged, setWhenParallelAction]
    NXTSensor:
        [resetScaledValue, getSensorReadings, getUpdateInterval,
        updateLastSensorValue, getLastSensorValue]
